#!/bin/bash

url_root="https://www.solarsystemscope.com/textures/download/"
folder="/mnt/d/Resources/3DModels/solar/"
names=("2k_mercury.jpg"
       "8k_mercury.jpg"
       "2k_venus_surface.jpg"
       "8k_venus_surface.jpg"
       "2k_venus_atmosphere.jpg"
       "4k_venus_atmosphere.jpg"
       "2k_mars.jpg"
       "8k_mars.jpg"
       "2k_jupiter.jpg"
       "8k_jupiter.jpg"
       "2k_saturn.jpg"
       "8k_saturn.jpg"
       "2k_saturn_ring_alpha.jpg"
       "8k_saturn_ring_alpha.jpg"
       "2k_uranus.jpg"
       "2k_neptune.jpg"
       "2k_earth_daymap.jpg"
       "8k_earth_daymap.jpg"
       "2k_earth_nightmap.jpg"
       "8k_earth_nightmap.jpg"
       "2k_earth_clouds.jpg"
       "8k_earth_clouds.jpg"
       "2k_earth_normal_map.tif"
       "8k_earth_normal_map.tif"
       "2k_earth_specular_map.tif"
       "8k_earth_specular_map.tif"
       "2k_stars.jpg"
       "8k_stars.jpg"
       "2k_stars_milky_way.jpg"
       "8k_stars_milky_way.jpg"
       "2k_sun.jpg"
       "8k_sun.jpg"
       "2k_moon.jpg"
       "8k_moon.jpg"
       "2k_ceres_fictional.jpg"
       "4k_ceres_fictional.jpg"
       "2k_haumea_fictional.jpg"
       "4k_haumea_fictional.jpg"
       "2k_makemake_fictional.jpg"
       "4k_makemake_fictional.jpg"
       "2k_eris_fictional.jpg"
       "4k_eris_fictional.jpg"
      )

for name in "${names[@]}"
do
    url=$url_root$name
    echo "Downloading $url..."
    wget --show-progress -P $folder $url
done
